config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'diaries#index'
  resources :diaries
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
class Diary < ApplicationRecord
  enum sleep: { 全く眠れなかった: 0, 少し眠れなかった: 8, 眠れた: 15, 少し眠れた: 22, よく眠れた: 30 }
  enum meal: { 食欲がなかった: 0, 野菜は摂れなかった: 8, 少し野菜が摂れた: 15, 意識して野菜を摂れた: 22, バランス良く摂れた: 30 }
  enum motion: { 運動しなかった: 0, 少し運動した: 8, ３０分以上は運動した: 15, １時間は運動した: 22, ２時間は運動した: 30 }
  enum study: { 勉強できなかった: 0, ３０分勉強した: 8, １時間勉強した: 15, ２時間勉強した: 22, ３時間以上勉強した: 30 }
  enum output: { 何もアウトプットできなかった: 0, ツイッターなどでアウトプットした: 8, 誰かと専門的な話をした: 15, 知り合いに勉強を教えた: 22, 他人に勉強を教えた: 30 }
  enum today_goal: { 目標は達成されなかった: 0, 目標を達成できそうだった: 8, 今日の目標を達成した: 15, 今週の目標も達成した: 22, 今月の目標も達成した: 30 }
  enum margin: { 心の余裕がない: 0, 少し心の余裕がない: 8, 少し心の余裕がある: 15, 心の余裕がある: 22, だいぶ心の余裕がある: 30 }
  enum tired: { まったく動けない: 0, 疲れて動けない: 8, 少し疲れた: 15, 疲れを感じなかった: 22, むしろ元気になった: 30 }
  enum refresh: { リフレッシュする時間がなかった: 0, 少しだけリフレッシュした: 8, リフレッシュした: 15, 半日リフレッシュできた: 22, １日リフレッシュできた: 30 }

  with_options presence: true do
    validates :sentence
    validates :sleep
    validates :meal
    validates :motion
    validates :study
    validates :output
    validates :today_goal
    validates :margin
    validates :tired
    validates :refresh
  end

  belongs_to :user
  has_one :status
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true

  has_many :diaries
  has_many :statuses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_diary, only: %i[show destroy edit update]
  before_action :different_diary, only: %i[edit update destroy]

  def index
    if user_signed_in?
      @diaries = Diary.where(user_id: current_user.id)
      @sleep_ave = @diaries.average(:sleep)
      @meal_ave = @diaries.average(:meal)
      @motion_ave = @diaries.average(:motion)
      @study_ave = @diaries.average(:study)
      @output_ave = @diaries.average(:output)
      @today_ave = @diaries.average(:today_goal)
      @margin_ave = @diaries.average(:margin)
      @tired_ave = @diaries.average(:tired)
      @refresh_ave = @diaries.average(:refresh)
      @heart_ave = (@margin_ave + @tired_ave + @refresh_ave).ceil
      @technique_ave = (@study_ave + @output_ave + @today_ave).ceil
      @body_ave = (@sleep_ave + @meal_ave + @motion_ave).ceil
    end
  end

  def new
    @diary = Diary.new
  end

  def show
    @sleep = @diary.sleep_before_type_cast
    @meal = @diary.meal_before_type_cast
    @motion = @diary.motion_before_type_cast
    @study = @diary.study_before_type_cast
    @output = @diary.output_before_type_cast
    @today_goal = @diary.today_goal_before_type_cast
    @margin = @diary.margin_before_type_cast
    @tired = @diary.tired_before_type_cast
    @refresh = @diary.refresh_before_type_cast
    @body = @sleep + @meal + @motion
    @technique = @study + @output + @today_goal
    @heart = @margin + @tired + @refresh
  end

  def create
    @diary = Diary.new(diary_params)
    if @diary.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    if @diary.user_id == current_user.id
      @diary.destroy
      redirect_to root_path, notice: '削除しました'
    end
  end

  def edit; end

  def update
    if @diary.update(diary_params)
      redirect_to diaries_path, notice: '編集しました'
    else
      render :edit
    end
  end

  private

  def diary_params
    params.require(:diary).permit(:sentence, :sleep, :meal, :motion, :study, :output, :today_goal, :margin, :tired,
                                  :refresh, :start_time).merge(user_id: current_user.id)
  end

  def set_diary
    @diary = Diary.find(params[:id])
  end

  def different_diary
    redirect_to action: :index if current_user.id != @diary.user_id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/views/diaries/edit.html.erb
<%= form_with model: @diary, local: true do |form| %>

<%= render 'layouts/error_messages', model: form.object %>


  <div class="time">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="sentence">
    <div class="select">
      <%= form.label :日記 %>
    </div>
    <div>
      <%= form.text_area :sentence %>
    </div>
  </div>

  <div class="sleep">
    <span class="select">睡眠</span><br>
    <div class="question">
      <div class="radio">
        <%= form.radio_button :sleep, :全く眠れなかった, ckecked: "checked" %>
        <%= form.label :全く眠れなかった, class: "select_label" %>
      </div>
      <div class="radio">
        <%= form.radio_button :sleep, :少し眠れなかった %>
        <%= form.label :少し眠れなかった, class: "select_label" %>
      </div>
      <div class="radio">
        <%= form.radio_button :sleep, :眠れた %>
        <%= form.label :眠れた, class: "select_label" %>
      </div>
      <div class="radio">
        <%= form.radio_button :sleep, :少し眠れた %>
        <%= form.label :少し眠れた, class: "select_label" %>
      </div>
      <div class="radio">
        <%= form.radio_button :sleep, :よく眠れた %>
        <%= form.label :よく眠れた, class: "select_label" %>
      </div>
    </div>
  </div>

  <div class="meal">
    <span class="select">食事</span><br>
    <div class="question">
      <div class="radio">
        <%= form.radio_button :meal, :食欲がなかった, ckecked: "checked" %>
        <%= form.label :食欲がなかった, class: "select_label" %>
      </div>
      <div class="radio">
        <%= form.radio_button :meal, :野菜は摂れなかった %>
        <%= form.label :野菜は摂れなかった, class: "select_label" %>
      </div>
      <div class="radio">
        <%= form.radio_button :meal, :少し野菜が摂れた %>
        <%= form.label :少し野菜が摂れた, class: "select_label" %>
      </div>
      <div class="radio">
        <%= form.radio_button :meal, :意識して野菜を摂れた %>
        <%= form.label :意識して野菜を摂れた, class: "select_label" %>
      </div>
      <div class="radio">
        <%= form.radio_button :meal, :バランス良く摂れた %>
        <%= form.label :バランス良く摂れた, class: "select_label" %>
      </div>
    </div>
  </div>

  <div class="motion">
    <span class="select">運動</span><br>
    <div class="question">
      <div class="radio">
        <%= form.radio_button :motion, :運動しなかった, ckecked: "checked" %>
        <%= form.label :運動しなかった, class: "select_label" %>
      </div>
      <div class="radio">
        <%= form.radio_button :motion, :少し運動した %>
        <%= form.label :少し運動した, class: "select_label" %>
      </div>
      <div class="radio">
        <%= form.radio_button :motion, :３０分以上は運動した %>
        <%= form.label :３０分以上は運動した, class: "select_label" %>
      </div>
      <div class="radio">
        <%= form.radio_button :motion, :１時間は運動した %>
        <%= form.label :１時間は運動した, class: "select_label" %>
      </div>
      <div class="radio">
        <%= form.radio_button :motion, :２時間は運動した %>
        <%= form.label :２時間は運動した, class: "select_label" %>
      </div>
    </div>
  </div>

  <div class="study">
    <span class="select">勉強</span><br>
    <div class="question">
      <div class="radio">
        <%= form.radio_button :study, :勉強できなかった, ckecked: "checked" %>
        <%= form.label :勉強できなかった, class: "select_label" %>
      </div>
      <div class="radio">
        <%= form.radio_button :study, :３０分勉強した %>
        <%= form.label :３０分勉強した, class: "select_label" %>
      </div>
      <div class="radio">
        <%= form.radio_button :study, :１時間勉強した %>
        <%= form.label :１時間勉強した, class: "select_label" %>
      </div>
      <div class="radio">
        <%= form.radio_button :study, :２時間勉強した %>
        <%= form.label :２時間勉強した, class: "select_label" %>
      </div>
      <div class="radio">
        <%= form.radio_button :study, :３時間以上勉強した %>
        <%= form.label :３時間以上勉強した, class: "select_label" %>
      </div>
    </div>
  </div>
    
  <div class="output">
    <span class="select">アウトプット</span><br>
    <div class="question">
      <div class="radio">
        <%= form.radio_button :output, :何もアウトプットできなかった, ckecked: "checked" %>
        <%= form.label :何もアウトプットできなかった, class: "select_label" %>
      </div>
      <div class="radio">
        <%= form.radio_button :output, :ツイッターなどでアウトプットした %>
        <%= form.label :ツイッターなどでアウトプットした, class: "select_label" %>
      </div>
      <div class="radio">
        <%= form.radio_button :output, :誰かと専門的な話をした %>
        <%= form.label :誰かと専門的な話をした, class: "select_label" %>
      </div>
      <div class="radio">
        <%= form.radio_button :output, :知り合いに勉強を教えた %>
        <%= form.label :知り合いに勉強を教えた, class: "select_label" %>
      </div>
      <div class="radio">
        <%= form.radio_button :output, :他人に勉強を教えた %>
        <%= form.label :他人に勉強を教えた, class: "select_label" %>
      </div>
    </div>
  </div>

  <div class="today_goal">
    <span class="select">今日・今週・今月の目標</span><br>
    <div class="question">
      <div class="radio">
        <%= form.radio_button :today_goal, :目標は達成されなかった, ckecked: "checked" %>
        <%= form.label :目標は達成されなかった, class: "select_label" %>
      </div>
      <div class="radio">
        <%= form.radio_button :today_goal, :目標を達成できそうだった %>
        <%= form.label :目標を達成できそうだった, class: "select_label" %>
      </div>
      <div class="radio">
        <%= form.radio_button :today_goal, :今日の目標を達成した %>
        <%= form.label :今日の目標を達成した, class: "select_label" %>
      </div>
      <div class="radio">
        <%= form.radio_button :today_goal, :今週の目標も達成した %>
        <%= form.label :今週の目標も達成した, class: "select_label" %>
      </div>
      <div class="radio">
        <%= form.radio_button :today_goal, :今月の目標も達成した %>
        <%= form.label :今月の目標も達成した, class: "select_label" %>
      </div>
    </div>
  </div>

  <div class="margin">
    <span class="select">心の余裕</span><br>
    <div class="question">
      <div class="radio">
        <%= form.radio_button :margin, :心の余裕がない, ckecked: "checked" %>
        <%= form.label :心の余裕がない, class: "select_label" %>
      </div>
      <div class="radio">
        <%= form.radio_button :margin, :少し心の余裕がない %>
        <%= form.label :少し心の余裕がない, class: "select_label" %>
      </div>
      <div class="radio">
        <%= form.radio_button :margin, :少し心の余裕がある %>
        <%= form.label :少し心の余裕がある, class: "select_label" %>
      </div>
      <div class="radio">
        <%= form.radio_button :margin, :心の余裕がある %>
        <%= form.label :心の余裕がある, class: "select_label" %>
      </div>
      <div class="radio">
        <%= form.radio_button :margin, :だいぶ心の余裕がある %>
        <%= form.label :だいぶ心の余裕がある, class: "select_label" %>
      </div>
    </div>
  </div>

  <div class="tired">
    <span class="select">疲労感</span><br>
    <div class="question">
      <div class="radio">
        <%= form.radio_button :tired, :まったく動けない, ckecked: "checked" %>
        <%= form.label :まったく動けない, class: "select_label" %>
      </div>
      <div class="radio">
        <%= form.radio_button :tired, :疲れて動けない %>
        <%= form.label :疲れて動けない, class: "select_label" %>
      </div>
      <div class="radio">
        <%= form.radio_button :tired, :少し疲れた %>
        <%= form.label :少し疲れた, class: "select_label" %>
      </div>
      <div class="radio">
        <%= form.radio_button :tired, :疲れを感じなかった %>
        <%= form.label :疲れを感じなかった, class: "select_label" %>
      </div>
      <div class="radio">
        <%= form.radio_button :tired, :むしろ元気になった %>
        <%= form.label :むしろ元気になった, class: "select_label" %>
      </div>
    </div>
  </div>

  <div class="refresh">
    <span class="select">リフレッシュ</span><br>
    <div class="question">
      <div class="radio">
        <%= form.radio_button :refresh, :リフレッシュする時間がなかった, ckecked: "checked" %>
        <%= form.label :リフレッシュする時間がなかった, class: "select_label" %>
      </div>
      <div class="radio">
        <%= form.radio_button :refresh, :少しだけリフレッシュした %>
        <%= form.label :少しだけリフレッシュした, class: "select_label" %>
      </div>
      <div class="radio">
        <%= form.radio_button :refresh, :リフレッシュした %>
        <%= form.label :リフレッシュした, class: "select_label" %>
      </div>
      <div class="radio">
        <%= form.radio_button :refresh, :半日リフレッシュできた %>
        <%= form.label :半日リフレッシュできた, class: "select_label" %>
      </div>
      <div class="radio">
        <%= form.radio_button :refresh, :１日リフレッシュできた %>
        <%= form.label :１日リフレッシュできた, class: "select_label" %>
      </div>
    </div>
  </div>


  <div class="submit">
    <%= form.submit "日記を保存する" ,class: :btn_new %>
    <%= link_to '削除', diary_path(@diary), method: :delete, data: { confirm: '本当に削除しますか？' }, class: :btn_new %>
    <%=link_to 'もどる', root_path, class: :btn_new %>
  </div>

<% end %>

app/views/diaries/index.html.erb
<% if user_signed_in? %>
  <p id="notice"><%= notice %></p>

  <div class="current-name">
    <%= "#{current_user.nickname}さんの日記" %>
  </div>

  <%= month_calendar events: @diaries do |date, diaries| %>
    <%= date.day %>

    <% diaries.each do |diary| %>
      <div>
        <%= link_to '日記を見る', diary %>
      </div>
    <% end %>
  <% end %>

  <div class="current-name">
    <%= "#{current_user.nickname}さんの状態" %>
  </div>
  <% if @diaries.present? %>
    <div class="htb-status">
      <div class="htb-body">
        <div class="body-status-name">
          <p>精神</p>
        </div>
        <div class="body-status-average">
          <img src="/assets/元気なハート.jpg" alt="精神" class="status-image">
          <div class="status-number">
            <%= "#{@heart_ave}点" %>
          </div>
        </div>
      </div>
      <div class="htb-body">
        <div class="body-status-name">
          <p>技術</p>
        </div>
        <div class="body-status-average">
          <img src="/assets/技術.jpg" alt="技術" class="status-image">
          <div class="status-number">
            <%= "#{@technique_ave}点" %>
          </div>
        </div>
      </div>
      <div class="htb-body">
        <div class="body-status-name">
          <p>体力</p>
        </div>
        <div class="body-status-average">
          <img src="/assets/走る人.jpg" alt="体力" class="status-image">
          <div class="status-number">
            <%= "#{@body_ave}点" %>
          </div>
        </div>
      </div>
    </div>
    <div class="current-name">
      <%= "#{current_user.nickname}さんにオススメの動画" %>
    </div>
    <div class="htb-video">
      <% if @heart_ave <= @technique_ave && @heart_ave <= @body_ave %>
        <iframe width="350" height="250" src="https://www.youtube.com/embed/ABpORnclGqc" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <iframe width="350" height="250" src="https://www.youtube.com/embed/LQLjk850-e4" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <iframe width="350" height="250" src="https://www.youtube.com/embed/qsQgqNpuhks" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <% elsif @technique_ave <= @heart_ave && @technique_ave <= @body_ave %>
        <iframe width="350" height="250" src="https://www.youtube.com/embed/qWiHBJaQbEw" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <iframe width="350" height="250" src="https://www.youtube.com/embed/KoukFuP7eO0" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <iframe width="350" height="250" src="https://www.youtube.com/embed/bi_WFrOYhgg" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <% elsif @body_ave <= @technique_ave && @body_ave <= @heart_ave %>
        <iframe width="350" height="250" src="https://www.youtube.com/embed/1nmW7eILIDA" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <iframe width="350" height="250" src="https://www.youtube.com/embed/cQsupVhKcDg" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <iframe width="350" height="250" src="https://www.youtube.com/embed/hge3fr50o0o" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <% else %>
        <p>現在、オススメできる動画がありません</p>
      <% end %>
    </div>
  <% end %>

  <div class="body_btn">
    <%= link_to '日記を書く', new_diary_path, class: :btn_body %>
  </div>

  <table>
    <thead>
      <tr class="diary-history">
        <th>最近書いた日記</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @diaries.last(7).each do |diary| %>
        <tr class="diary-history">
          <td><%= diary.start_time.strftime("%Y年%m月%d日") %></td>
          <td><%= link_to '詳細', diary, class: :diary_history_btn %></td>
          <td><%= link_to '編集', edit_diary_path(diary.id), class: :diary_history_btn %></td>
          <td><%= link_to '削除', diary_path(diary.id), method: :delete, data: { confirm: '本当に削除しますか？' }, class: :diary_history_btn %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
<% else %>
<div>
  <%= image_tag "人混み.jpg", class: "main-image" %>
</div>
<h1 class="htb-main">ハテボチェッカーとは？</h1>
<div class="htb-sub">
<p>近年、ストレス社会と呼ばれるくらい自分をコントロールすることが難しい世の中になりました。</p>
<p>そこで、ハテボチェッカーを利用することで自分の体力・技術・精神がどれくらいなのかを点数し、自分の状態を客観的に見る事ができます！</p>
<p>自分の状態を把握して、今日の目標やスケジュールを立てるのに役立ててください！</p>
</div>
<p class="htb-st3">ハテボチェッカーの利用方法は、簡単３ステップです！</p>
<ul class="htb-step">
  <li>
    <img src="/assets/会員登録.jpg" alt="会員登録" class="step-image">
    <p class="step-name">①会員登録する</p>
  </li>
  <li>
    <img src="/assets/日記.jpg" alt="日記" class="step-image">
    <p class="step-name">②日記を書く</p>
  </li>
  <li>
    <img src="/assets/日記確認.jpg" alt="日記確認" class="step-image">
    <p class="step-name">③トップページで今の状態を確認する！</p>
  </li>
</ul>
<div class="htb-sub2">
<p>日記を見るボタンをクリックすれば日記の詳細（その日の状態）を見ることできます。</p>
<p>また、日記は後で修正することもできますし、消すこともできます！</p>
</div>

<p class="htb-sub3">さぁ！ハテボチェッカーを試してみよう！</p>
<div class="body_btn">
  <%= link_to '新規登録', new_user_registration_path, class: :btn_body %>
</div>
<% end %>

app/views/diaries/show.html.erb
<p id="notice"><%= notice %></p>

  <div class="htb-status">
    <div class="htb-body">
      <div class="body-status-name">
        <p>精神</p>
      </div>
      <div class="body-status-average">
        <img src="/assets/元気なハート.jpg" alt="精神" class="status-image">
        <div class="status-number">
          <%= "#{@heart}点" %>
        </div>
      </div>
    </div>
    <div class="htb-body">
      <div class="body-status-name">
        <p>技術</p>
      </div>
      <div class="body-status-average">
        <img src="/assets/技術.jpg" alt="技術" class="status-image">
        <div class="status-number">
          <%= "#{@technique}点" %>
        </div>
      </div>
    </div>
    <div class="htb-body">
      <div class="body-status-name">
        <p>体力</p>
      </div>
      <div class="body-status-average">
        <img src="/assets/走る人.jpg" alt="体力" class="status-image">
        <div class="status-number">
          <%= "#{@body}点" %>
        </div>
      </div>
    </div>
  </div>

  <ul class="show-list">
    <li class="show-number">
      <p>日にち：</p>
      <%= @diary.start_time.strftime("%Y年%m月%d日") %>
    </li>
    <li class="show-number">
      <p>日記：</p>
      <%= @diary.sentence %>
    </li>
    <li class="show-number">
      <p>睡眠：</p>
      <%= @diary.sleep %>
    </li>
    <li class="show-number">
      <p>食事：</p>
      <%= @diary.meal %>
    </li>
    <li class="show-number">
      <p>運動：</p>
      <%= @diary.motion %>
    </li>
    <li class="show-number">
      <p>勉強：</p>
      <%= @diary.study %>
    </li>
    <li class="show-number">
      <p>アウトプット：</p>
      <%= @diary.output %>
    </li>
    <li class="show-number">
      <p>今日・今週・今月の目標：</p>
      <%= @diary.today_goal %>
    </li>
    <li class="show-number">
      <p>心の余裕：</p>
      <%= @diary.margin %>
    </li>
    <li class="show-number">
      <p>疲労感：</p>
      <%= @diary.tired %>
    </li>
    <li class="show-number">
      <p>リフレッシュ：</p>
      <%= @diary.refresh %>
    </li>
  </ul>

  <div class="submit">
    <%= link_to '編集する', edit_diary_path(@diary), class: :btn_new %>
    <%= link_to '削除', diary_path(@diary), method: :delete, data: { confirm: '本当に削除しますか？' }, class: :btn_new %>
    <%= link_to 'もどる', root_path, class: :btn_new %>
  </div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Htbcheker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="header">
    <div class="nav">
      <div class="header__bar">
        <h1><%= link_to 'ハテボチェッカー', root_path, class: "header-name"%></h1>
      </div>
      <ul class='lists-right'>
      <% if user_signed_in? %>
        <li><%= link_to "#{current_user.nickname}さん", "#", class: "user-nickname" %></li>
        <li><%= link_to '日記を書く', new_diary_path, class: "user-nickname" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: :nav__btn %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: :nav__btn %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: :nav__btn %></li>
      <% end %>
      </ul>
    </div>
  </header>
    <%= yield %>
    <footer class="footer">
      <p class="footer-name">
        ハテボチェッカー 2021
      </p>
    </footer>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>